apiVersion: v2
name: query
description: A Helm chart to Query backend databases

type: application

version: 0.19.0

appVersion: "0.18.0"

maintainers:
  - name: Siak Hooi

icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAACXBIWXMAAAsTAAALEwEAmpwYAAADmElEQVR4nO1cz0sVURT+2miQtiiIzCdBpa8I2rRr5apVui9btYkyFy2yoHV/RFHtTX0Wme2L1kFGIu4qKMp+vGebp8mJA9/ARXw0zoxz5s7cD+5iLs6dz4975pzz3VEgICAgICAgICAgIMAEAwBmALQAiCdDuTYA1Isg3o8CCJJ0KPeapYAzJPLCmsgOoVwXyP2JJZEWSfgknhs9yr1pSUI4fIU5f7Em4Dt/sSbgO38xItApqyZdxwwSBPRTwNLwF2sCvvMXawK+8xdrAr7zb5agE/ltSWKWJBZIyBco15fkPm1JZGiLGxPhDYDXBb523ZhBGKLeQUAl+6rA14URsFECO0stOTM0QxLxvAzwnb9YE/Cdv1gT8J2/BDcmCChV3IGl4S/WBHznL9YEfOcv1gR8598MnUg6zAY7Kx2Ggp2VDvVgZ6VDI9hZ6dAMScTzMiAl1q35izWBlOgHcM+SgHguoDmkAHbW3Q7Hljd4dLkE4A/HEs9CxotyhiOGAv4FcHWbkLwPYCPGB+ab/D76KAwhBQrhUeeb7TaAKQAXWavu46hzboo/I7xnpOoCTnBHCdvLYzHuOe7UsZsM+UoKOEoBdNxKcP+kc/9I1QTsd8I2iXiuiNGfPPShQp3IQyds02KOa2kSqoSdNcBM3I75zvsfTrAz2eDOLrWdBb70hRk1K0xzzesouZ0F5+MgLUuywhjXnEcF7KxlPlujIMsNIexYSp9EWnx2b4Zr9jrFdenLmBaf3ZPhmvurJODyLoTwSa65ggoIuMBnX8pwzctc8zkqIOD4LpYx2luXXsAai942jYG0GGQh3c4zKYpxL/yAz9dyKg32AHjGtbQ9RFUEPOJkYzUEkuIO11jNs40rgoCgBRXZUZMJdt5tx0u8gpwhBRAw6osjEeZoDMR55z3dYvO/B3AIFf23JxeczmidGXWMtV0PxymWKtPOmfAqd94irxfzFLFRsK+z+nZwqNRmwtD3KCiaK6LWgr8APALQnZcbIzkP9QNvbsNLE8E1mhwfAKzxWHOFwkx0iBpXRHfM76aINR4PRuFjMTQSDmf0+8w7u3AYwLc8RCwT1ijYeV6fBvA1iBgfjynWdwBnOKfJ50sQMR66nK7kJ4CznFfX5zPn9ZORvTHXqyS6OoioteOnIGI8dDsJxQ1nLdI/cl7DPSCBiOfydq7LJKKWNu/yNl7L9E6MxlsAB62JwSPoTtR3noat7sgDOvsPk9Sc8Q+xnhEAAAAASUVORK5CYII=
