name: Build helm chart

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - run: cat release.env >> $GITHUB_ENV
      - run: helm lint deploy/helm/${{ env.HELM_CHART_NAME }}/
      - run: helm template ${{ env.HELM_CHART_NAME }}-release-1 deploy/helm/${{ env.HELM_CHART_NAME }}/
      - run: helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - run: bin/helm-unit-test.sh
      - run: helm package deploy/helm/${{ env.HELM_CHART_NAME }}/

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: helm-chart
          path: ${{ env.HELM_CHART_NAME }}-${{ env.HELM_CHART_VERSION }}.tgz
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6.0.0
        with:
          name: helm-unit-test.xml
          path: helm-unit-test.xml
