name: Build docker images

on:
  workflow_dispatch:
  workflow_call:
      secrets:
        REGISTRY_PASSWORD_DOCKER:
          required: true
        PUBLISH_TO_GITHUB_REPO_TOKEN:
          required: true
      inputs:
        push-images:
          required: true
          type: boolean

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v7
        with:
          name: deliverables
          path: ./
      - run: ls -l
      - run: cat release.env >> $GITHUB_ENV
      - uses: docker/login-action@v3
        if: ${{ inputs.push-images }}
        with:
          username: ${{ env.REGISTRY_USERNAME_DOCKER }}
          password: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
      - uses: docker/login-action@v3
        if: ${{ inputs.push-images }}
        with:
          registry: ghcr.io
          username: ${{ env.REGISTRY_USERNAME_GHCR }}
          password: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./deploy/docker/Dockerfile
          push: ${{ inputs.push-images }}
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_VERSION }}
            ${{ env.DOCKER_IMAGE_NAME_GHCR }}:latest
            ${{ env.DOCKER_IMAGE_NAME_GHCR }}:${{ env.DOCKER_VERSION }}
