name: Build docker images

on:
  workflow_dispatch:
  workflow_call:
      secrets:
        REGISTRY_PASSWORD_DOCKER:
          required: true
        PUBLISH_TO_GITHUB_REPO_TOKEN:
          required: true
      inputs:
        push-images:
          required: true
          type: boolean

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: deliverables
          path: ./

      - run: ls -l
      - run: cat release.env >> $GITHUB_ENV

      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: ${{ inputs.push-images }}
        with:
          username: ${{ env.REGISTRY_USERNAME_DOCKER }}
          password: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: ${{ inputs.push-images }}
        with:
          registry: ghcr.io
          username: ${{ env.REGISTRY_USERNAME_GHCR }}
          password: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}

      - uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: ./
          file: ./deploy/docker/Dockerfile
          push: ${{ inputs.push-images }}
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_VERSION }}
            ${{ env.DOCKER_IMAGE_NAME_GHCR }}:latest
            ${{ env.DOCKER_IMAGE_NAME_GHCR }}:${{ env.DOCKER_VERSION }}
