name: Publish to siakhooi.github.io/helm-charts

on:
  workflow_call:
    secrets:
      PUBLISH_TO_GITHUB_REPO_TOKEN:
        required: true

jobs:
  publish_to_helm_charts:
    name: publish to helm charts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: helm-chart
          path: ./

      - run: ./.github/bin/deploy-to-siakhooi-helm-charts.sh
        env:
          PUBLISH_TO_GITHUB_REPO_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
