name: Build and Test on Push
on:
  push:
    branches:
      - "*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-with-maven:
    uses: ./.github/workflows/build-with-maven.yml

  sonarcloud:
    needs: build-with-maven
    uses: ./.github/workflows/quality-sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  qltysh:
    needs: build-with-maven
    uses: ./.github/workflows/quality-qltysh.yml
    secrets:
      QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}

  build-docker-images:
    needs: build-with-maven
    uses: ./.github/workflows/build-docker-image.yml
    secrets:
      PUBLISH_TO_GITHUB_REPO_TOKEN: ${{ secrets.PUBLISH_TO_GITHUB_REPO_TOKEN }}
      REGISTRY_PASSWORD_DOCKER: ${{ secrets.REGISTRY_PASSWORD_DOCKER }}
    with:
      push-images: false

  build-helm-chart:
    uses: ./.github/workflows/build-helm-chart.yml
